### ISSUE TITLE
Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by Rudloff** [vackosar/ytcapd#1]
Hello,

I'm getting this error when I run `gradlew`:
```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

I think the `gradle/wrapper/` directory is missing.

**Comment by vackosar** [comment]
hm, I dont have the project checked out and in original state, so I cant check how I got it setup. But this doesnt seem like something that couldnt be resolved with some StackOverflowing. Is it possible that you need to configure your own version of Gradle executable somewhere?

**Comment by Rudloff** [comment]
Yes, I can install Gradle myself.
But projects that include a `gradlew` file usually do it so that contributors can easily run the correct Gradle version. But for this you need `gradle/wrapper/gradle-wrapper.properties` and `gradle/wrapper/gradle-wrapper.jar` files. I think you can generate them with the `gradle wrapper` command.

If you don't want/don't have time to do this, I suggest you remove the `gradlew` file and document which Gradle version the project requires.

**Comment by vackosar** [comment]
Thks a lot for valid suggestion. If u have working version would u submit a PR?

**Comment by Rudloff** [comment]
I can submit a PR but I will need to know what version of Gradle is needed.

**Comment by vackosar** [comment]
thankfully I found a backup and added gradle wrapper. Can u confirm?

**Comment by Rudloff** [comment]
gradlew now works. Thanks!
